spring:
  application:
    name: xue-ai-agent
  profiles:
    active: local
  mvc:
    pathmatch:
      # 解决Spring Boot 3.x中路径匹配问题（关键！）
      matching-strategy: ant_path_matcher
  ai:
    dashscope:
      api-key: sk-2595cb835134452d9fae6c929f0c54b5
    chat:
      options:
      model: qwen-plus

  datasource:
    # 核心修改：PostgreSQL 连接地址（替换为你的实例信息）
    url: jdbc:postgresql://rm-cn-0yf4phhqb0002ago.rwlb.rds.aliyuncs.com:5432/health_ai_agent?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    # PostgreSQL 用户名（你的高权限账号，比如 root）
    username: xjj
    # PostgreSQL 密码（你的实例密码）
    password: Xue123456
    # PostgreSQL 驱动类（必须改）
    driver-class-name: org.postgresql.Driver
    # 可选：连接池配置（提升性能）
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000

server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi config
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.xue.aiagent_me.controller
# knife4j config
knife4j:
  enable: true
  setting:
    language: zh_cn